settings:
  title: '緒山みはりの監視パネルです'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: '所有站点运行正常'
  notAllmonitorsOperational: '有站点状态异常！'
  monitorLabelOperational: '运行中'
  monitorLabelNotOperational: '宕机中'
  monitorLabelNoData: '无数据'
  dayInHistogramNoData: '无数据'
  dayInHistogramOperational: '很好'
  dayInHistogramNotOperational: ' 事件' # xx incident(s) recorded

monitors:
  - id: pan-gongyun-xyz # unique identifier
    name: pan.gongyun.xyz
    description: '公云存储主页' # default=empty
    url: 'https://pan.gongyun.xyz/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: wiki-gongyun-xyz
    name: wiki.gongyun.xyz
    description: '公云存储使用文档'
    url: 'https://wiki.gongyun.xyz/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: pan-spx233-top
    name: panbaidu-url-pull
    description: '度盘分享直链提取'
    url: 'pan.senapi.net'
    method: GET
    expectStatus: 200

  - id: gytk-lol
    name: gytk.lol
    description: '短链接转换'
    url: 'https://gytk.lol/'
    method: GET
    expectStatus: 200

  - id: kemono-su
    name: kemono.su（单纯验证域名是否正常）
    description: '漫画图库'
    url: 'https://kemono.su/'
    method: GET
    expectStatus: 200

  - id: pan1-panbaidu-link
    name: 公云前端 1 号
    url: 'https://pan1.panbaidu.link/'
    method: GET
    expectStatus: 200
    linkable: false

  - id: pan2-panbaidu-link
    name: 公云前端 2 号
    url: 'https://pan2.panbaidu.link/'
    method: GET
    expectStatus: 200
    linkable: false

  - id: pan3-panbaidu-link
    name: 公云前端 3 号
    url: 'https://pan3.panbaidu.link/'
    method: GET
    expectStatus: 200
    linkable: false

  - id: mysql-panbaidu-link
    name: 公云后端
    url: 'https://mysql.panbaidu.link/'
    method: GET
    expectStatus: 200
    linkable: false
